/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projettitib.IHM;

import projettitib.classe.Couple;
import projettitib.classe.titib.Titib;

/**
 *
 * @author Titi
 */
public class Connexion extends javax.swing.JFrame {
    Couple couple ;

    /**
     * Creates new form Connexion
     * @param amoureux
     */
    public Connexion(Couple amoureux) {
        this.couple = amoureux ;
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSurnom = new javax.swing.JLabel();
        jTextFieldSurnom = new javax.swing.JTextField();
        jLabelMdp = new javax.swing.JLabel();
        jPasswordFieldMdp = new javax.swing.JPasswordField();
        jLabelMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonConnexion = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connexion");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Welcome to TitibCorporation"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(90, 60));
        jPanel2.setPreferredSize(new java.awt.Dimension(308, 93));
        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabelSurnom.setText("Surnom :");
        jLabelSurnom.setName(""); // NOI18N
        jPanel2.add(jLabelSurnom);
        jPanel2.add(jTextFieldSurnom);

        jLabelMdp.setText("Mdp :");
        jPanel2.add(jLabelMdp);
        jPanel2.add(jPasswordFieldMdp);
        jPanel2.add(jLabelMessage);
        jPanel2.add(jLabel1);

        jButtonConnexion.setText("Connexion");
        jButtonConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnexionActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonConnexion);

        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonFermer);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        dispose() ;
    }//GEN-LAST:event_jButtonFermerActionPerformed

    private void jButtonConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnexionActionPerformed
        String surnom = jTextFieldSurnom.getText() ;
        String mdp = new String(jPasswordFieldMdp.getPassword()) ;
        if (surnom.trim().length() > 0) {
            if (mdp.trim().length() > 0) {
                Titib titibCo = couple.trouverTitib(surnom, mdp) ;
                if (titibCo != null) {
                    new InterfaceTitib(couple, titibCo).setVisible(true) ;
                    dispose() ;
                } else
                    jLabelMessage.setText("Identifiants invalides");
            } else
                jLabelMessage.setText("Mdp manquant");
        } else
            jLabelMessage.setText("Surnom manquant");
    }//GEN-LAST:event_jButtonConnexionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnexion;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMdp;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelSurnom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldMdp;
    private javax.swing.JTextField jTextFieldSurnom;
    // End of variables declaration//GEN-END:variables
}
