/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projettitib.IHM;

import projettitib.classe.titib.Titib;

/**
 *
 * @author Sow
 */
public class dialogueAttribuerPoints extends javax.swing.JDialog {
    Titib titibInLove ;

    /**
     * Creates new form dialogueAttribuerPoints
     * @param parent
     * @param modal
     * @param titibInLove
     */
    public dialogueAttribuerPoints(java.awt.Frame parent, boolean modal, Titib titibInLove) {
        super(parent, modal);
        this.titibInLove = titibInLove ;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerNbPoints = new javax.swing.JSpinner();
        jButtonAttribuer = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Nombre points :");
        jPanel1.add(jLabel1);
        jPanel1.add(jSpinnerNbPoints);

        jButtonAttribuer.setText("Attribuer");
        jButtonAttribuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttribuerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAttribuer);

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAnnuler);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        dispose() ;
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonAttribuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttribuerActionPerformed
        int nbPoints = (Integer) jSpinnerNbPoints.getModel().getValue() ;
        if (nbPoints > 0) {
            titibInLove.ajouterPoints(nbPoints);
            dispose();
        }
    }//GEN-LAST:event_jButtonAttribuerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonAttribuer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerNbPoints;
    // End of variables declaration//GEN-END:variables
}
