/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projettitib.IHM;

import javax.swing.DefaultListModel;
import javax.swing.border.TitledBorder;
import javax.swing.table.AbstractTableModel;
import projettitib.classe.titib.Amoureuse;
import projettitib.classe.titib.Amoureux;
import projettitib.classe.Couple;
import projettitib.classe.bon.Bon;
import projettitib.classe.titib.Titib;
import projettitib.modif.TableAchatBonModel;
import projettitib.modif.TableVenteBonModel;
/**
 *
 * @author Titi
 */
public class InterfaceTitib extends javax.swing.JFrame {
    private final Couple couple ;
    private final Titib titibCo ;
    private Titib titibInLoveWith ;
    
    private void initListVosBonsAchetes() {
        DefaultListModel model = new DefaultListModel() ;
        jListVosBonAchete.setModel(model) ;
        for (Bon bon : titibCo.getListeBonsAchetes().getListeBons()) {
            model.addElement(bon) ;
        }
    }
    
    private void initListSesBonsAchetes() {
        DefaultListModel model = new DefaultListModel() ;
        jListSesBonsAchetes.setModel(model) ;
        for (Bon bon : titibInLoveWith.getListeBonsAchetes().getListeBons()) {
            model.addElement(bon) ;
        }
    }

    /**
     * Creates new form InterfaceTitib
     * @param amoureux
     * @param titibCo
     */
    public InterfaceTitib(Couple amoureux, Titib titibCo) {
        this.couple = amoureux ;
        this.titibCo = titibCo ;
        initComponents();
        
        titibInLoveWith = couple.getAutre(titibCo) ;
        if (titibCo instanceof Amoureux)
            jLabelTitre.setText(titibCo.toString()+" amoureux de "+titibInLoveWith.toString());
        else if (titibCo instanceof Amoureuse)
            jLabelTitre.setText(titibCo.toString()+" amourese de "+titibInLoveWith.toString());
        initListVosBonsAchetes();
        initListSesBonsAchetes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonSupprBon = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVente = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListVosBonAchete = new javax.swing.JList<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonAchatBon = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAchat = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListSesBonsAchetes = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 500));
        setPreferredSize(new java.awt.Dimension(400, 500));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setRequestFocusEnabled(false);
        jPanel2.add(jLabelTitre);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Maison "+titibCo.getMaison()+" "+titibCo.getNbPoints()+ " points"));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jButtonSupprBon.setText("Supprimer");
        jButtonSupprBon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprBonActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonSupprBon);

        jPanel4.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jTableVente.setModel(new TableVenteBonModel(titibCo));
        jScrollPane2.setViewportView(jTableVente);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bons achetés"));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(110, 130));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(110, 130));

        jScrollPane3.setViewportView(jListVosBonAchete);

        jPanel8.add(jScrollPane3, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Vous", jPanel4);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jButtonAchatBon.setText("Acheter");
        jButtonAchatBon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAchatBonActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonAchatBon);

        jPanel10.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jTableAchat.setModel(new TableAchatBonModel(couple, titibCo));
        jScrollPane1.setViewportView(jTableAchat);

        jPanel11.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bons achetés"));
        jScrollPane4.setMinimumSize(new java.awt.Dimension(110, 130));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(110, 130));

        jScrollPane4.setViewportView(jListSesBonsAchetes);

        jPanel11.add(jScrollPane4, java.awt.BorderLayout.EAST);

        jPanel10.add(jPanel11, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Votre <3", jPanel10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Compte");

        jMenuItem3.setText("Attribuer points");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Déconnexion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vente");

        jMenuItem2.setText("Ajouter bon");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose() ;
        new Connexion(couple).setVisible(true) ;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new dialogueAjoutBon(this, true, titibCo).setVisible(true);
        jTableVente.setModel(new TableVenteBonModel(titibCo));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonAchatBonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAchatBonActionPerformed
        TableAchatBonModel model = (TableAchatBonModel) jTableAchat.getModel() ;
        int selectedRow = jTableAchat.getSelectedRow() ;
        if (selectedRow != -1) {
            int cout = (Integer) model.getValueAt(selectedRow, 0) ;
            String nom = (String) model.getValueAt(selectedRow, 1) ;
            Bon bon = titibInLoveWith.getListeBons().trouverBon(nom, cout) ;
            if (titibCo.acheterBon(bon, titibInLoveWith)) {
                model.removeRow(selectedRow) ;
                initListVosBonsAchetes();
                jPanel3.setBorder(new TitledBorder(null,"Maison "+titibCo.getMaison()+" "+titibCo.getNbPoints()+ " points", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));
            }
        }
    }//GEN-LAST:event_jButtonAchatBonActionPerformed

    private void jButtonSupprBonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprBonActionPerformed
        TableVenteBonModel model = (TableVenteBonModel) jTableVente.getModel() ;
        int selectedRow = jTableVente.getSelectedRow() ;
        if (selectedRow != -1) {
            int cout = (Integer) model.getValueAt(selectedRow, 0) ;
            String nom = (String) model.getValueAt(selectedRow, 1) ;
            Bon bon = titibCo.getListeBons().trouverBon(nom, cout) ;
            titibCo.getListeBons().supprimerBon(bon);
            model.removeRow(selectedRow) ;
        }
    }//GEN-LAST:event_jButtonSupprBonActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new dialogueAttribuerPoints(this, true, titibInLoveWith).setVisible(true); ;
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAchatBon;
    private javax.swing.JButton jButtonSupprBon;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JList<String> jListSesBonsAchetes;
    private javax.swing.JList<String> jListVosBonAchete;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableAchat;
    private javax.swing.JTable jTableVente;
    // End of variables declaration//GEN-END:variables
}
